apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: puppetdb
  labels:
    app: puppet
    role: db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: puppet
        role: db
    spec:
      volumes:
      - name: puppetdbssl
        hostPath:
          path: /etc/puppetdb/ssl
      hostname: puppetdb
      nodeSelector:
        node: download
      containers:
      - name: puppetdb
        image: puppet/puppetdb
        ports:
        - containerPort: 8081
          name: ssl
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: puppetdbssl
          mountPath: /etc/puppetlabs/puppet/ssl/

---
apiVersion: v1
kind: Service
metadata:
  name: puppetdb
spec:
  ports:
  - name: puppetdb
    port: 8081
    targetPort: 8081
  selector:
    app: puppet
    role: db
