apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: puppet
  labels:
    app: puppet
    role: server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: puppet
        role: server
    spec:
      volumes:
      - name: puppetcode
        hostPath:
          path: /etc/puppet/code
      - name: puppetssl
        hostPath:
          path: /etc/puppet/ssl
      - name: puppetdata
        hostPath:
          path: /etc/puppet/data
      hostname: puppet
      nodeSelector:
        node: download
      containers:
      - name: puppet
        image: puppet/puppetserver
        env:
        - name: PUPPETDB_SERVER_URLS
          value: https://puppetdb:8081
        ports:
        - containerPort: 8140
        volumeMounts:
        - name: puppetcode
          mountPath: /etc/puppetlabs/code/
        - name: puppetssl
          mountPath: /etc/puppetlabs/puppet/ssl/
        - name: puppetdata
          mountPath: /opt/puppetlabs/server/data/puppetserver/

---
apiVersion: v1
kind: Service
metadata:
  name: puppet
  labels:
    app: puppet
    role: server
spec:
  selector:
    app: puppet
    role: server
  ports:
    - port: 8140
      name: puppet
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: puppet
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/auth-type: "basic"
    ingress.kubernetes.io/auth-secret: "mysecret"
    prometheus.io/scrape: 'true'
spec:
  rules:
  - host: puppetserver.mcth.fr
    http:
      paths:
      - backend:
          serviceName: puppet
          servicePort: 8140
